#!/bin/bash
:<<doc
This takes the cluster maps and punches out the values of each subject's L2M,
and M2L for making histograms later.

Masks are located in: 
/Volumes/fmri/Music/withinHist
these masks were generated by taking the significant voxels inside each ActPass
region (based on the previous randomise, in 6mm_across_permutation_CogForum),
and using them to punch out the univariate clusters.
doc
projectDir=/Volumes/fmri/Music
dataDir=${projectDir}/Maps/6mm_100/raw
outDir=${projectDir}/withinHist
maskDir=${projectDir}/masks/StructureClusterMasks
cd ${outDir}
rm ${outDir}/*_cluster?.txt
for sub in Mus001 Mus003 Mus005 Mus006 Mus007 Mus008 Mus009 Mus010 Mus011 Mus012 \
	Mus013 Mus014 Mus015 Mus016 Mus017 Mus019 Mus020 Mus021 Mus022 Mus023
do
for clust in 1 2 3 4 5
do
# make significance maps, e.g. those that surpass threshold
# fslmaths ${sub}_L2M_rMap.nii.gz -sub 
# making cluster map
	echo ${sub} cluster${clust}
	fslmaths ${sub}_L2M_sig.nii.gz -bin L2M_sig.nii.gz
	fslmaths ${maskDir}/${sub}_mask_overlap_3mm_cluster${clust}.nii.gz -bin \
		-add L2M_sig.nii.gz -thr 1.5 -bin -mas \
		${projectDir}/masks/${sub}/3mm_mask_Ctx_uniOverlap.hdr \
		${sub}_L2M_cluster${clust}_overlap.nii.gz
	fslmaths ${sub}_M2L_sig.nii.gz -bin M2L_sig.nii.gz
	fslmaths ${maskDir}/${sub}_mask_overlap_3mm_cluster${clust}.nii.gz -bin \
		-add M2L_sig.nii.gz -thr 1.5 -bin -mas \
		${projectDir}/masks/${sub}/3mm_mask_Ctx_uniOverlap.hdr \
		${sub}_M2L_cluster${clust}_overlap.nii.gz  
	rm L2M_sig.nii.gz
	rm M2L_sig.nii.gz
	fslmaths ${dataDir}/${sub}_grayMatterL2M_rMap.nii.gz -nan ${outDir}/${sub}_L2M_rMap.nii.gz
	fslmaths ${dataDir}/${sub}_grayMatterM2L_rMap.nii.gz -nan ${outDir}/${sub}_M2L_rMap.nii.gz
  echo ${sub} \
  `fslstats ${outDir}/${sub}_L2M_rMap.nii.gz -k ${outDir}/${sub}_L2M_cluster${clust}_overlap.nii.gz -M -S -R -V` >> ${outDir}/L2M_cluster${clust}.txt
  echo ${sub} \
  `fslstats  ${outDir}/${sub}_M2L_rMap.nii.gz -k ${outDir}/${sub}_M2L_cluster${clust}_overlap.nii.gz -M -S -R -V` >> ${outDir}/M2L_cluster${clust}.txt

done
done
